version: 2
updates:

  - package-ecosystem: docker
    directory: /.devcontainer
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore(deps)
